#ifndef __AudioPlayerPanelImp__
#define __AudioPlayerPanelImp__

/**
@file
Subclass of pnlPlayer, which is generated by wxFormBuilder.
*/

#include "AudioPlayerPanel.h"
#include "AudioPlayer.h"
#include "AudioPlayerPanelTimer.h"

//// end generated include

/** Implementing pnlPlayer */
class AudioPlayerPanelImp : public pnlPlayer
{

	AudioPlayer* player;
	boost::signals2::connection onUrlConnection;
	boost::signals2::connection onAudioEndConnection;
	boost::signals2::connection onClearUrlConnection;
	void OnAudioURL();
	void OnAudioEnd();
	void OnClearURL();
	AudioPlayerPanelTimer timer;

protected:
	void PlayOnButtonClick(wxCommandEvent& event);

	public:
		/** Constructor */
		AudioPlayerPanelImp( wxWindow* parent, AudioPlayer* player);
		~AudioPlayerPanelImp();
	//// end generated class members
		void Play();

	
};

#endif // __AudioPlayerPanelImp__
