#ifndef __ExercisePanelImp__
#define __ExercisePanelImp__

/**
@file
Subclass of ExercisePanel, which is generated by wxFormBuilder.
*/

#include "ExercisePanel.h"
#include "ExerciseViewModel.h"

//// end generated include

#include "AudioPlayer.h"
#include "AudioPlayerPanelImp.h"
#include "CommandProperty.h"

/** Implementing ExercisePanel */
class ExercisePanelImp : public ExercisePanel
{
	ExerciseViewModel viewModel;
	AudioPlayer playerQuestion;
	AudioPlayerPanelImp* playerPanelQuestion;
	AudioPlayer playerAnswer;
	AudioPlayerPanelImp* playerPanelAnswer;

	void Update();
	void RenderTopics();
	void RenderQuiz();
	void RenderQuestions();
	void RenderCurrentQuestion();
	bool ValidateQuiz();
	bool ValidateQuestion();
	bool SaveCheck();
	void BindQuestion();
	void DisableQuestion();
	void EnableQuestion();
	void RecordQuestion();
	void RecordAnswer();
	void AddQuestion();
	void DeleteQuestion();
	void SetupSpeechHandlers();
	void OnCommandRecognized(std::wstring& phrase, const std::vector<CommandProperty>& commandPropertyList);

	protected:
		// Handlers for ExercisePanel events.
		void ExercisePanelOnInitDialog( wxInitDialogEvent& event );
		void NameOnKillFocus( wxFocusEvent& event );
		void NameOnSetFocus( wxFocusEvent& event );
		void NameOnText(wxCommandEvent& event);
		void AddQuestionOnButtonClick( wxCommandEvent& event );
		void DeleteQuestionOnButtonClick( wxCommandEvent& event );
		void DeleteQuestionOnUpdateUI( wxUpdateUIEvent& event );
		void QuestionsSelectionChanged( wxDataViewEvent& event );
		void RecordQuestionOnButtonClick( wxCommandEvent& event );
		void ClearQuestionOnButtonClick( wxCommandEvent& event );
		void RecordAnswerOnButtonClick( wxCommandEvent& event );
		void ClearAnswerOnButtonClick( wxCommandEvent& event );
		void ApplyOnButtonClick( wxCommandEvent& event );
		void CancelOnButtonClick( wxCommandEvent& event );
		void CancelOnUpdateUI(wxUpdateUIEvent& event);
		void ApplyOnUpdateUI(wxUpdateUIEvent& event);
		void TopicsOnCombobox(wxCommandEvent& event);
		void QuestionOnText(wxCommandEvent& event);
		void AnswerOnText(wxCommandEvent& event);
	
public:
		/** Constructor */
		ExercisePanelImp( wxWindow* parent, Publication* publication );
		ExercisePanelImp(wxWindow* parent, Publication* publication, Quiz* quiz);
		~ExercisePanelImp();
	//// end generated class members


};

#endif // __ExercisePanelImp__
