#ifndef __ExerciseRunDialogImp__
#define __ExerciseRunDialogImp__

/**
@file
Subclass of ExerciseRunDialog, which is generated by wxFormBuilder.
*/

#include "ExerciseRunDialog.h"

//// end generated include

#include "Quiz.h"
#include "ExerciseRunViewModel.h"
#include "ApplicationImages.h"
#include "AudioPlayer.h"

/** Implementing ExerciseRunDialog */
class ExerciseRunDialogImp : public ExerciseRunDialog
{
	wxIcon deleteIcon;
	ExerciseRunViewModel viewModel;
	AudioPlayer player;
	void RenderQuestions();
	void SetQuestion(QuizRunQuestion& question);

	protected:
		// Handlers for ExerciseRunDialog events.
		void CloseOnButtonClick( wxCommandEvent& event );
		void OnInitDialog(wxInitDialogEvent& event);
		void RecordOnButtonClick(wxCommandEvent& event);
		void AudioPlayOnButtonClick(wxCommandEvent& event);


	public:
		/** Constructor */
		ExerciseRunDialogImp( wxWindow* parent, unsigned long quizId );
	//// end generated class members
	
};

#endif // __ExerciseRunDialogImp__
