#ifndef __ExportDialogImp__
#define __ExportDialogImp__

/**
@file
Subclass of ExportDialog, which is generated by wxFormBuilder.
*/

#include "ExportDialog.h"

//// end generated include

/** Implementing ExportDialog */
class ExportDialogImp : public ExportDialog
{
	protected:
		// Handlers for ExportDialog events.
		void OnOKButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		ExportDialogImp( wxWindow* parent );
	//// end generated class members
	
};

#endif // __ExportDialogImp__
