#ifndef __PublicationDialogImp__
#define __PublicationDialogImp__

/**
@file
Subclass of PublicationDialog, which is generated by wxFormBuilder.
*/

#include "PublicationDialog.h"

//// end generated include

#include "stdafx.h"
#include "CommandProperty.h"

/** Implementing PublicationDialog */
class PublicationDialogImp : public PublicationDialog
{
private:
	short _type;
	std::vector<std::wstring> ruleNames;
	void OnCommandRecognized(std::wstring& phrase, const std::vector<CommandProperty>& commandPropertyList);
	void DisableWindow(bool flag);

	protected:
		void OnInitDialog( wxInitDialogEvent& event );
		void OnOKButtonClick( wxCommandEvent& event );
		void TitleOnKillFocus(wxFocusEvent& event);
		void TitleOnSetFocus(wxFocusEvent& event);
		void TypesOnKillFocus(wxFocusEvent& event);
		void TypesOnSetFocus(wxFocusEvent& event);


	public:
		/** Constructor */
		PublicationDialogImp( wxWindow* parent );
		~PublicationDialogImp();
		short GetType () const { return _type ; }
		void SetType(const short type) { _type = type;}
	//// end generated class members
	
};

#endif // __PublicationDialogImp__
