#ifndef __SAConfirmDialogImp__
#define __SAConfirmDialogImp__

/**
@file
Subclass of SAConfirmDialog, which is generated by wxFormBuilder.
*/

#include "SAConfirmDialog.h"

//// end generated include

#include "CommandProperty.h"

/** Implementing SAConfirmDialog */
class SAConfirmDialogImp : public SAConfirmDialog
{
	const wxString message;
	std::vector<std::wstring> ruleNames;
	void OnCommandRecognized(std::wstring& phrase, std::vector<CommandProperty> commandPropertyList);

	protected:
		// Handlers for SAConfirmDialog events.
		void OnInitDialog( wxInitDialogEvent& event );
		void NoButtonClick( wxCommandEvent& event );
		void YesButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		SAConfirmDialogImp( wxWindow* parent);
		SAConfirmDialogImp(wxWindow* parent, const wxString& title, const wxString& message);
		~SAConfirmDialogImp();
	//// end generated class members
	
};

#endif // __SAConfirmDialogImp__
