#ifndef __SegmentTemplateDialogImp__
#define __SegmentTemplateDialogImp__

/**
@file
Subclass of SegmentTemplateDialog, which is generated by wxFormBuilder.
*/

#include "SegmentTemplateDialog.h"
#include "SegmentTypeViewModel.h"
#include "FontBuilder.h"

//// end generated include

/** Implementing SegmentTemplateDialog */
class SegmentTemplateDialogImp : public SegmentTemplateDialog
{

	SegmentTypeViewModel* viewModel;
	FontBuilder fontBuilder;

	bool ValidateHeader();
	bool ValidateSegment();
	void RenderSegments();
	NoteSegmentType* FindSelectedNoteSegmentType(long id);
	void SendSegmentTypeToWindow();
	void GetSegmentTypeFromWindow();
	void EditItem();

	protected:
		// Handlers for SegmentTemplateDialog events.
		void OnInitDialog(wxInitDialogEvent& event);
		void AddUpdateOnButtonClick( wxCommandEvent& event );
		void NewOnButtonClick( wxCommandEvent& event );
		void RemoveOnButtonClick( wxCommandEvent& event );
		void RemoveOnUpdateUI( wxUpdateUIEvent& event );
		void OnCancelButtonClick( wxCommandEvent& event );
		void OnOKButtonClick( wxCommandEvent& event );
		void OnSegmentListSelectionChanged(wxDataViewEvent& event);
	public:
		/** Constructor */
		SegmentTemplateDialogImp( wxWindow* parent, SegmentTypeViewModel* viewModel );
	//// end generated class members

		SegmentTypeViewModel* GetViewModel() { return viewModel; }
	
};

#endif // __SegmentTemplateDialogImp__
