#ifndef __SettingsDialogImp__
#define __SettingsDialogImp__

/**
@file
Subclass of DlgSettings, which is generated by wxFormBuilder.
*/

#include "SettingsDialog.h"

//// end generated include

/** Implementing DlgSettings */
class SettingsDialogImp : public DlgSettings
{
	wxString dataDirectory;
	bool dataDirectoryDirty;
	protected:
		// Handlers for DlgSettings events.
		void OnInitDialog(wxInitDialogEvent& event);
		void OnOKButtonClick( wxCommandEvent& event );
		void DataDirectoryOnDirChanged(wxFileDirPickerEvent& event);
	public:
		/** Constructor */
		SettingsDialogImp( wxWindow* parent );
	//// end generated class members
		const wxString& const GetDataDirectory() { return dataDirectory; }
		void SetDataDirectory(const wxString& dataDirectory) { this->dataDirectory = dataDirectory; }
		const bool const GetDataDirectoryDirty() { return dataDirectoryDirty; }
};

#endif // __SettingsDialogImp__
