#ifndef __SettingsDialogImp__
#define __SettingsDialogImp__

/**
@file
Subclass of DlgSettings, which is generated by wxFormBuilder.
*/

#include "SettingsDialog.h"

//// end generated include

/** Implementing DlgSettings */
class SettingsDialogImp : public DlgSettings
{
	public:
		/** Constructor */
		SettingsDialogImp( wxWindow* parent );
	//// end generated class members
	
};

#endif // __SettingsDialogImp__
