#ifndef __SubjectDialogImp__
#define __SubjectDialogImp__

/**
@file
Subclass of SubjectDialog, which is generated by wxFormBuilder.
*/

#include "SubjectDialog.h"

//// end generated include
#include "stdafx.h"
#include "CommandProperty.h"

/** Implementing SubjectDialog */
class SubjectDialogImp : public SubjectDialog
{

	void OnCommandRecognized(std::wstring& phrase, std::vector<CommandProperty> commandPropertyList);

	public:
		/** Constructor */
		SubjectDialogImp( wxWindow* parent );

protected:
		void OnClose( wxCloseEvent& event );
		void OnInitDialog( wxInitDialogEvent& event );
		void OnOKButtonClick( wxCommandEvent& event );
	//// end generated class members
	
};

#endif // __SubjectDialogImp__
