#ifndef __TopicDialogImp__
#define __TopicDialogImp__

/**
@file
Subclass of TopicDialog, which is generated by wxFormBuilder.
*/

#include "TopicDialog.h"

//// end generated include

/** Implementing TopicDialog */
class TopicDialogImp : public TopicDialog
{
	protected:
		// Handlers for TopicDialog events.
		void OnCancelButtonClick( wxCommandEvent& event );
		void OnOKButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		TopicDialogImp( wxWindow* parent );
	//// end generated class members
	
};

#endif // __TopicDialogImp__
